// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMJLb3zXLBmpqFpclJ760bIl4QPT4yHc',
    appId: '1:234728091826:web:a2cdd057890a998f8159ab',
    messagingSenderId: '234728091826',
    projectId: 'presenceapp-pwpb',
    authDomain: 'presenceapp-pwpb.firebaseapp.com',
    storageBucket: 'presenceapp-pwpb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfws1r_mQazJkqsI_bmK41TnI8Rw57-ms',
    appId: '1:234728091826:android:2cbe382cf2dafd118159ab',
    messagingSenderId: '234728091826',
    projectId: 'presenceapp-pwpb',
    storageBucket: 'presenceapp-pwpb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDjbHFA18yGdrLZi3dumygf6AIdnderc',
    appId: '1:234728091826:ios:2ea5c1151768ba368159ab',
    messagingSenderId: '234728091826',
    projectId: 'presenceapp-pwpb',
    storageBucket: 'presenceapp-pwpb.appspot.com',
    iosClientId: '234728091826-g5ma7lomgcpv2oi5a69spv6uliigr3ak.apps.googleusercontent.com',
    iosBundleId: 'com.mrezkys.presence',
  );
}
